### ISSUE TITLE
Kickoff GOCD pipeline after files have been moved

### ISSUE THREAD

**Issue by redspart** [hung135/file_router#38]
Kickoff GOCD pipeline after successful move of files per project. 
- [x] new param that takes a GoCD pipeline URL for each project
- [x] Handle all errors that might occur
- [x] GoCD url is optional

**Comment by redspart** [comment]
Added functionality here 6d9a4600e1dec17183a17bd6df8fb960cb6c19f4

Issue may need to be reopened depending on version of GOCD

**Comment by redspart** [comment]
Added more functionality to the API caller here: e7e69332f3c9ac47bec1ab42bef0aa8c9de558e9

Since we _might_ have to deal with different versions of GoCD later down the road. @hung135 

For the yaml file you have to add:
```yaml
api:
    url: "https://example.io.something/go/api"
    pipeline: "name_of_pipelne"
```
